package tms;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author taimo
 */
public class Adminhome extends javax.swing.JFrame {

   
    public Adminhome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbladdpkg = new javax.swing.JLabel();
        lblavailablethings = new javax.swing.JLabel();
        lbladdfood = new javax.swing.JLabel();
        lbladdtransport = new javax.swing.JLabel();
        lblmodpkg = new javax.swing.JLabel();
        lbladdroom = new javax.swing.JLabel();
        lblmodpkg1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tourism Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/male_user_50px.png"))); // NOI18N
        jLabel6.setText("Welcome Home Admin!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 230, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Welcome Dear Admin!");
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 250, 60));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 400, 180));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_24px.png"))); // NOI18N
        jLabel3.setText("Home");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Features");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 20));

        lbladdpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbladdpkg.setForeground(new java.awt.Color(255, 255, 255));
        lbladdpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit_property_24px.png"))); // NOI18N
        lbladdpkg.setText("     Add Package");
        lbladdpkg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladdpkgMouseClicked(evt);
            }
        });
        jPanel2.add(lbladdpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 50));

        lblavailablethings.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblavailablethings.setForeground(new java.awt.Color(255, 255, 255));
        lblavailablethings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/template_26px.png"))); // NOI18N
        lblavailablethings.setText("Available things");
        lblavailablethings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblavailablethingsMouseClicked(evt);
            }
        });
        jPanel2.add(lblavailablethings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 40));

        lbladdfood.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbladdfood.setForeground(new java.awt.Color(255, 255, 255));
        lbladdfood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/categorize_24px.png"))); // NOI18N
        lbladdfood.setText("     Add Food");
        lbladdfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladdfoodMouseClicked(evt);
            }
        });
        jPanel2.add(lbladdfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, 40));

        lbladdtransport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbladdtransport.setForeground(new java.awt.Color(255, 255, 255));
        lbladdtransport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tiles_26px.png"))); // NOI18N
        lbladdtransport.setText("     Add Transport");
        lbladdtransport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladdtransportMouseClicked(evt);
            }
        });
        jPanel2.add(lbladdtransport, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 200, 40));

        lblmodpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblmodpkg.setForeground(new java.awt.Color(255, 255, 255));
        lblmodpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        lblmodpkg.setText("     See/Delete Customer's History");
        lblmodpkg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmodpkgMouseClicked(evt);
            }
        });
        jPanel2.add(lblmodpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 240, 40));

        lbladdroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbladdroom.setForeground(new java.awt.Color(255, 255, 255));
        lbladdroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grid_24px.png"))); // NOI18N
        lbladdroom.setText("     Add Room");
        lbladdroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladdroomMouseClicked(evt);
            }
        });
        jPanel2.add(lbladdroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 200, 40));

        lblmodpkg1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblmodpkg1.setForeground(new java.awt.Color(255, 255, 255));
        lblmodpkg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        lblmodpkg1.setText("     Delete Package");
        lblmodpkg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmodpkg1MouseClicked(evt);
            }
        });
        jPanel2.add(lblmodpkg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, 730));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\taimo\\Downloads\\2s.png")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1190, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbladdpkgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdpkgMouseClicked
        // TODO add your handling code here:
        Hotel add=new Hotel();
        add.show();
    }//GEN-LAST:event_lbladdpkgMouseClicked

    private void lblavailablethingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblavailablethingsMouseClicked
        // TODO add your handling code here:
        Userownlist list=new Userownlist();
        list.show();
    }//GEN-LAST:event_lblavailablethingsMouseClicked

    private void lbladdfoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdfoodMouseClicked
        Userownlist list=new Userownlist();
        list.show();        // TODO add your handling code here:
    }//GEN-LAST:event_lbladdfoodMouseClicked

    private void lbladdtransportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdtransportMouseClicked
        // TODO add your handling code here:
        Userownlist list=new Userownlist();
        list.show();
    }//GEN-LAST:event_lbladdtransportMouseClicked

    private void lblmodpkgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmodpkgMouseClicked

        Customerhistory his=new Customerhistory();
        his.show();
    }//GEN-LAST:event_lblmodpkgMouseClicked

    private void lbladdroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdroomMouseClicked
        Userownlist list=new Userownlist();
        list.show();        // TODO add your handling code here:
    }//GEN-LAST:event_lbladdroomMouseClicked

    private void lblmodpkg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmodpkg1MouseClicked
        // TODO add your handling code here:
        Hotel add=new Hotel();
        add.show();
    }//GEN-LAST:event_lblmodpkg1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbladdfood;
    private javax.swing.JLabel lbladdpkg;
    private javax.swing.JLabel lbladdroom;
    private javax.swing.JLabel lbladdtransport;
    private javax.swing.JLabel lblavailablethings;
    private javax.swing.JLabel lblmodpkg;
    private javax.swing.JLabel lblmodpkg1;
    // End of variables declaration//GEN-END:variables
}
