package tms;



import tms.Userview;
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author taimo
 */
public class Homescreen extends javax.swing.JFrame {

    /**
     * Creates new form Homescreen
     */
    public Homescreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnuserregister = new javax.swing.JButton();
        btnviewpkg = new javax.swing.JButton();
        btnadminlogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tourism Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel3.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnuserregister.setBackground(new java.awt.Color(0, 0, 0));
        btnuserregister.setForeground(new java.awt.Color(255, 255, 255));
        btnuserregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add2.png"))); // NOI18N
        btnuserregister.setText("Register as user");
        btnuserregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserregisterActionPerformed(evt);
            }
        });
        jPanel3.add(btnuserregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 160, 40));

        btnviewpkg.setBackground(new java.awt.Color(0, 0, 0));
        btnviewpkg.setForeground(new java.awt.Color(255, 255, 255));
        btnviewpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_26px.png"))); // NOI18N
        btnviewpkg.setText("View Packages");
        btnviewpkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewpkgActionPerformed(evt);
            }
        });
        jPanel3.add(btnviewpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 160, 40));

        btnadminlogin.setBackground(new java.awt.Color(0, 0, 0));
        btnadminlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnadminlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        btnadminlogin.setText("Login as Admin");
        btnadminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminloginActionPerformed(evt);
            }
        });
        jPanel3.add(btnadminlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 160, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 310, 250));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\taimo\\Downloads\\2s.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1190, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminloginActionPerformed
        // TODO add your handling code here:
        Home home=new Home();
        home.show();
    }//GEN-LAST:event_btnadminloginActionPerformed

    private void btnviewpkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewpkgActionPerformed
        // TODO add your handling code here:
       Viewdesti desti=new Viewdesti();
       desti.show();
    }//GEN-LAST:event_btnviewpkgActionPerformed

    private void btnuserregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserregisterActionPerformed
        // TODO add your handling code here:
        Userregister register=new Userregister();
        register.show();
    }//GEN-LAST:event_btnuserregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homescreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadminlogin;
    private javax.swing.JButton btnuserregister;
    private javax.swing.JButton btnviewpkg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
