/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author taimo
 */
public class Islamabad extends javax.swing.JFrame {
Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Connectclass cons=new Connectclass();
    Tbladdpkg tabl=new Tbladdpkg();
    DefaultTableModel d;
    /**
     * Creates new form Islamabad
     */
    public Islamabad() {
        initComponents();
         cons.Connect();
         tabl.tbli(tblisl);
    }
 public void mouse(){
     d=(DefaultTableModel)tblisl.getModel();
        int sIndex=tblisl.getSelectedRow();
        combopkgplace.setSelectedItem(d.getValueAt(sIndex,0).toString());
        txtnoofdays.setText(d.getValueAt(sIndex,1).toString());
        combopkgtype.setSelectedItem(d.getValueAt(sIndex,2).toString());
        combohotelname.setSelectedItem(d.getValueAt(sIndex,3).toString());
        comboroomtype.setSelectedItem(d.getValueAt(sIndex,4).toString());
        comboroomsize.setSelectedItem(d.getValueAt(sIndex,5).toString());
        combofoodtype.setSelectedItem(d.getValueAt(sIndex,6).toString());
        txtcostofpkg.setText(d.getValueAt(sIndex,7).toString());
        btnaddpkg.setEnabled(true);
    }
    public void reset(){
     btnaddpkg.setEnabled(true);
        combopkgplace.setSelectedItem("Select Your destiny");
        txtnoofdays.setText("");
        combopkgtype.setSelectedItem("Choose your package");
        combohotelname.setSelectedItem("Select your hotel");
        comboroomtype.setSelectedItem("Select your room type");
        comboroomsize.setSelectedItem("Select room size");
        combofoodtype.setSelectedItem("Select your food type");
        txtcostofpkg.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblnoofdays = new javax.swing.JLabel();
        lblpkgroomsize = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblisl = new javax.swing.JTable();
        lblpkgplace = new javax.swing.JLabel();
        txtnoofdays = new javax.swing.JTextField();
        lblpkgcost = new javax.swing.JLabel();
        lblpkgroomtype = new javax.swing.JLabel();
        txtcostofpkg = new javax.swing.JTextField();
        lblpkgtype = new javax.swing.JLabel();
        lblpkghotelname = new javax.swing.JLabel();
        combopkgplace = new javax.swing.JComboBox<>();
        combopkgtype = new javax.swing.JComboBox<>();
        btnaddpkg = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        lblfoodname = new javax.swing.JLabel();
        lblfoodtype1 = new javax.swing.JLabel();
        combohotelname = new javax.swing.JComboBox<>();
        comboroomtype = new javax.swing.JComboBox<>();
        comboroomsize = new javax.swing.JComboBox<>();
        combofoodname = new javax.swing.JComboBox<>();
        combofoodtype = new javax.swing.JComboBox<>();
        btndelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tourism Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/male_user_50px.png"))); // NOI18N
        jLabel6.setText("Welcome Home Admin!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 230, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Add Package");
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 160, 30));

        lblnoofdays.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnoofdays.setForeground(new java.awt.Color(255, 255, 255));
        lblnoofdays.setText("No of Days");
        jPanel5.add(lblnoofdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 20));

        lblpkgroomsize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgroomsize.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgroomsize.setText("Room Size");
        jPanel5.add(lblpkgroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 100, 20));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 20));

        tblisl.setBackground(new java.awt.Color(0, 0, 0));
        tblisl.setForeground(new java.awt.Color(255, 255, 255));
        tblisl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Package Place", "No of Days", "Package Type", "Hotel Name", "Room Type", "Room Size", "Food Type", "Package Cost "
            }
        ));
        tblisl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblislMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblisl);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 840, 260));

        lblpkgplace.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgplace.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgplace.setText("Package Place");
        jPanel5.add(lblpkgplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 20));
        jPanel5.add(txtnoofdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, 30));

        lblpkgcost.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgcost.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgcost.setText("Package Cost");
        jPanel5.add(lblpkgcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 100, 20));

        lblpkgroomtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgroomtype.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgroomtype.setText("Room Type");
        jPanel5.add(lblpkgroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 20));
        jPanel5.add(txtcostofpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 220, 30));

        lblpkgtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgtype.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgtype.setText("Package Type");
        jPanel5.add(lblpkgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 20));

        lblpkghotelname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkghotelname.setForeground(new java.awt.Color(255, 255, 255));
        lblpkghotelname.setText("Hotel Name");
        jPanel5.add(lblpkghotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 20));

        combopkgplace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your destiny ", "islamabad", " " }));
        jPanel5.add(combopkgplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 220, 30));

        combopkgtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose your package", "Golden", "Bronze", "Silver" }));
        jPanel5.add(combopkgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 220, 30));

        btnaddpkg.setBackground(new java.awt.Color(0, 0, 0));
        btnaddpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnaddpkg.setForeground(new java.awt.Color(255, 255, 255));
        btnaddpkg.setText("Confirm");
        btnaddpkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddpkgActionPerformed(evt);
            }
        });
        jPanel5.add(btnaddpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        btncancel.setBackground(new java.awt.Color(0, 0, 0));
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        jPanel5.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        lblfoodname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodname.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodname.setText("Food Name");
        jPanel5.add(lblfoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 80, 20));

        lblfoodtype1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodtype1.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodtype1.setText("Food Type");
        jPanel5.add(lblfoodtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 100, 20));

        combohotelname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your hotel", "Freddy's Luxury Apartment", "Chalet islamabad", "The Mark", " " }));
        jPanel5.add(combohotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 220, 30));

        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your room type", "AC", "NON-AC", " " }));
        jPanel5.add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 220, 30));

        comboroomsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select room size", "Single ", "Double", " " }));
        jPanel5.add(comboroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 220, 30));

        combofoodname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Biryani", "Chowmin", "Noodles", "Pasta ", "Eggs Benedict", "Lobster Newburg", "Peach Melba", "Soup", "Ramen", "Potato Chips", "Donuts", "Ice Cream", "Chicken Tenders", "Soft Drinks/Soda", "Pizza", "Oreo Cookies", "French Fries" }));
        jPanel5.add(combofoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 220, 30));

        combofoodtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your food type", "Veg", "Non-veg", " " }));
        combofoodtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combofoodtypeActionPerformed(evt);
            }
        });
        jPanel5.add(combofoodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 220, 30));

        btndelete.setBackground(new java.awt.Color(0, 0, 0));
        btndelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 860, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblislMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblislMouseClicked
        // TODO add your handling code here
        mouse();
    }//GEN-LAST:event_tblislMouseClicked

    private void btnaddpkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddpkgActionPerformed
        // TODO add your handling code here:
        Adminaddpkg p=new Adminaddpkg();
        p.adminisl((String)combopkgplace.getSelectedItem(),Integer.parseInt( txtnoofdays.getText()), (String)combopkgtype.getSelectedItem(), (String)combohotelname.getSelectedItem(), (String)comboroomtype.getSelectedItem(), (String)comboroomsize.getSelectedItem(), (String)combofoodtype.getSelectedItem(), Double.parseDouble(txtcostofpkg.getText()));
        tabl.tbli(tblisl);
        reset();
    }//GEN-LAST:event_btnaddpkgActionPerformed

    private void combofoodtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combofoodtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combofoodtypeActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        Adminaddpkg del=new Adminaddpkg();
        del.dellhr((String)combohotelname.getSelectedItem(),Integer.parseInt( txtnoofdays.getText()));
        tabl.tbli(tblisl);
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Islamabad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Islamabad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Islamabad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Islamabad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Islamabad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddpkg;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JComboBox<String> combofoodname;
    private javax.swing.JComboBox<String> combofoodtype;
    private javax.swing.JComboBox<String> combohotelname;
    private javax.swing.JComboBox<String> combopkgplace;
    private javax.swing.JComboBox<String> combopkgtype;
    private javax.swing.JComboBox<String> comboroomsize;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfoodname;
    private javax.swing.JLabel lblfoodtype1;
    private javax.swing.JLabel lblnoofdays;
    private javax.swing.JLabel lblpkgcost;
    private javax.swing.JLabel lblpkghotelname;
    private javax.swing.JLabel lblpkgplace;
    private javax.swing.JLabel lblpkgroomsize;
    private javax.swing.JLabel lblpkgroomtype;
    private javax.swing.JLabel lblpkgtype;
    private javax.swing.JTable tblisl;
    private javax.swing.JTextField txtcostofpkg;
    private javax.swing.JTextField txtnoofdays;
    // End of variables declaration//GEN-END:variables
}
