/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms;

import java.awt.Color;

/**
 *
 * @author taimo
 */
public class Karachi extends javax.swing.JFrame {

    /**
     * Creates new form Karachi
     */
    public Karachi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbladdpkg = new javax.swing.JLabel();
        lblavailablethings = new javax.swing.JLabel();
        lbladdfood = new javax.swing.JLabel();
        lbladdtransport = new javax.swing.JLabel();
        lblmodpkg = new javax.swing.JLabel();
        lblmodroom = new javax.swing.JLabel();
        lbladdroom = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblvehiclename = new javax.swing.JLabel();
        lblroomsize = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btnconfirm = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtfoodcost = new javax.swing.JTextField();
        lblvehicletype = new javax.swing.JLabel();
        txtvehiclecost = new javax.swing.JTextField();
        lblfoodname = new javax.swing.JLabel();
        lblroomtype = new javax.swing.JLabel();
        txttotalcost = new javax.swing.JTextField();
        lbltranstype = new javax.swing.JLabel();
        lblvehiclecost = new javax.swing.JLabel();
        lbltotalcost = new javax.swing.JLabel();
        lblfoodtype = new javax.swing.JLabel();
        combofoodtype = new javax.swing.JComboBox<>();
        combotranstype = new javax.swing.JComboBox<>();
        combovehicletype = new javax.swing.JComboBox<>();
        comboroomtype = new javax.swing.JComboBox<>();
        comboroomsize = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblhotelname = new javax.swing.JLabel();
        lblroomsize1 = new javax.swing.JLabel();
        txthotelcost = new javax.swing.JTextField();
        lblfoodtype1 = new javax.swing.JLabel();
        lblroomtype1 = new javax.swing.JLabel();
        txtnoofpersons = new javax.swing.JTextField();
        combovehiclename = new javax.swing.JComboBox<>();
        combohotelname = new javax.swing.JComboBox<>();
        combofoodname = new javax.swing.JComboBox<>();
        btnconfirm2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tourism Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/male_user_50px.png"))); // NOI18N
        jLabel6.setText("Welcome Home Admin!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 230, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_24px.png"))); // NOI18N
        jLabel3.setText("Home");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Features");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 20));

        lbladdpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbladdpkg.setForeground(new java.awt.Color(255, 255, 255));
        lbladdpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit_property_24px.png"))); // NOI18N
        lbladdpkg.setText("     Add Package");
        jPanel2.add(lbladdpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 50));

        lblavailablethings.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblavailablethings.setForeground(new java.awt.Color(255, 255, 255));
        lblavailablethings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/template_26px.png"))); // NOI18N
        lblavailablethings.setText("Available things");
        jPanel2.add(lblavailablethings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 40));

        lbladdfood.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbladdfood.setForeground(new java.awt.Color(255, 255, 255));
        lbladdfood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/categorize_24px.png"))); // NOI18N
        lbladdfood.setText("     Add Food");
        jPanel2.add(lbladdfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, 40));

        lbladdtransport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbladdtransport.setForeground(new java.awt.Color(255, 255, 255));
        lbladdtransport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tiles_26px.png"))); // NOI18N
        lbladdtransport.setText("     Add Transport");
        jPanel2.add(lbladdtransport, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 200, 40));

        lblmodpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblmodpkg.setForeground(new java.awt.Color(255, 255, 255));
        lblmodpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        lblmodpkg.setText("     Modify/Delete Package");
        jPanel2.add(lblmodpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 40));

        lblmodroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblmodroom.setForeground(new java.awt.Color(255, 255, 255));
        lblmodroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        lblmodroom.setText("     Modify/Delete Choice");
        jPanel2.add(lblmodroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 200, 40));

        lbladdroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbladdroom.setForeground(new java.awt.Color(255, 255, 255));
        lbladdroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grid_24px.png"))); // NOI18N
        lbladdroom.setText("     Add Room");
        jPanel2.add(lbladdroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 730));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Available Things");
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 180, 30));

        lblvehiclename.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblvehiclename.setForeground(new java.awt.Color(255, 255, 255));
        lblvehiclename.setText("Vehicle Name");
        jPanel5.add(lblvehiclename, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, 20));

        lblroomsize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblroomsize.setForeground(new java.awt.Color(255, 255, 255));
        lblroomsize.setText("Room Size");
        jPanel5.add(lblroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 100, 20));

        btncancel.setBackground(new java.awt.Color(0, 0, 0));
        btncancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel5.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 70, -1));

        btnconfirm.setBackground(new java.awt.Color(0, 0, 0));
        btnconfirm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnconfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });
        jPanel5.add(btnconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 80, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 20));
        jPanel5.add(txtfoodcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 200, 30));

        lblvehicletype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblvehicletype.setForeground(new java.awt.Color(255, 255, 255));
        lblvehicletype.setText("Vehicle Type");
        jPanel5.add(lblvehicletype, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 110, 20));
        jPanel5.add(txtvehiclecost, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 210, 30));

        lblfoodname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodname.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodname.setText("Food Name");
        jPanel5.add(lblfoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 80, 20));

        lblroomtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblroomtype.setForeground(new java.awt.Color(255, 255, 255));
        lblroomtype.setText("Room Type");
        jPanel5.add(lblroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 100, 20));
        jPanel5.add(txttotalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 200, 30));

        lbltranstype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbltranstype.setForeground(new java.awt.Color(255, 255, 255));
        lbltranstype.setText("Transport Type");
        jPanel5.add(lbltranstype, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 100, 20));

        lblvehiclecost.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblvehiclecost.setForeground(new java.awt.Color(255, 255, 255));
        lblvehiclecost.setText("Vehicle cost");
        jPanel5.add(lblvehiclecost, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, 20));

        lbltotalcost.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbltotalcost.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalcost.setText("Total Cost");
        jPanel5.add(lbltotalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 100, 20));

        lblfoodtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodtype.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodtype.setText("Food Cost");
        jPanel5.add(lblfoodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 100, 20));

        combofoodtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your food type", "Veg", "Non-veg", " " }));
        combofoodtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combofoodtypeActionPerformed(evt);
            }
        });
        jPanel5.add(combofoodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 200, 30));

        combotranstype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your transport type", "Airplan", "Car", "Bus", "Mini-Bus" }));
        jPanel5.add(combotranstype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 210, 30));

        combovehicletype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your vehicle type", "AC", "NON-AC" }));
        jPanel5.add(combovehicletype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 210, 30));

        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your room type", "AC", "NON-AC", " " }));
        jPanel5.add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 210, 30));

        comboroomsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select room size", "Single ", "Double", " " }));
        jPanel5.add(comboroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 200, 30));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Transport Type", "Vehicle Type", "Vehicle Name", "Vehicle Cost", "Hotel Name", "Room Type", "Room Size", "Hotel Cost", "Food Name", "Food Type", "Food Cost", "Total Cost"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 950, 270));

        lblhotelname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblhotelname.setForeground(new java.awt.Color(255, 255, 255));
        lblhotelname.setText("Hotel Name");
        jPanel5.add(lblhotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, 20));

        lblroomsize1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblroomsize1.setForeground(new java.awt.Color(255, 255, 255));
        lblroomsize1.setText("Hotel Cost");
        jPanel5.add(lblroomsize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 100, 20));
        jPanel5.add(txthotelcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 200, 30));

        lblfoodtype1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodtype1.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodtype1.setText("Food Type");
        jPanel5.add(lblfoodtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 100, 20));

        lblroomtype1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblroomtype1.setForeground(new java.awt.Color(255, 255, 255));
        lblroomtype1.setText("No of Persons");
        jPanel5.add(lblroomtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 100, 20));
        jPanel5.add(txtnoofpersons, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 200, 30));

        combovehiclename.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Vehicle brand", "DHL", "UPS", "FedEx" }));
        jPanel5.add(combovehiclename, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 210, 30));

        combohotelname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your hotel", "Hotel One mall road", "Hotel one bhurban", "The smart Hotel" }));
        jPanel5.add(combohotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, 30));

        combofoodname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your food ", "Biryani", "Chowmin", "Noodles", "Pasta ", "Eggs Benedict", "Lobster Newburg", "Peach Melba", "Soup", "Ramen", "Potato Chips", "Donuts", "Ice Cream", "Chicken Tenders", "Soft Drinks/Soda", "Pizza", "Oreo Cookies", "French Fries" }));
        jPanel5.add(combofoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 200, 30));

        btnconfirm2.setBackground(new java.awt.Color(0, 0, 0));
        btnconfirm2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnconfirm2.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirm2.setText("Check Price");
        btnconfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirm2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnconfirm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 120, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 950, 580));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\taimo\\Downloads\\2s.png")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1190, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
        Adminchoicee c=new Adminchoicee();
        Double vc=Double.parseDouble(txtvehiclecost.getText());
        Double hc=Double.parseDouble(txthotelcost.getText());
        Double fc=Double.parseDouble(txtfoodcost.getText());
        Double tc=Double.parseDouble(txttotalcost.getText());
        c.adminchoic((String)combotranstype.getSelectedItem(),(String)combovehicletype.getSelectedItem(),(String)combovehiclename.getSelectedItem(),vc, (String)combohotelname.getSelectedItem(), (String)comboroomtype.getSelectedItem(), (String)comboroomsize.getSelectedItem(),hc, (String)combofoodtype.getSelectedItem(),fc,tc);
//c.adminchoic((String)combotranstype.getSelectedItem(),(String)combovehicletype.getSelectedItem(),(String)combovehiclename.getSelectedItem(),txtvehiclecost.getText(), (String)combohotelname.getSelectedItem(),(String)comboroomtype.getSelectedItem(), (String)comboroomsize.getSelectedItem(),txthotelcost.getText(), (String)combofoodname.getSelectedItem(), (String)combofoodtype.getSelectedItem(),txtfoodcost.getText(),txttotalcost.getText());
   
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void combofoodtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combofoodtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combofoodtypeActionPerformed

    private void btnconfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfirm2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karachi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karachi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karachi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karachi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karachi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JButton btnconfirm2;
    private javax.swing.JComboBox<String> combofoodname;
    private javax.swing.JComboBox<String> combofoodtype;
    private javax.swing.JComboBox<String> combohotelname;
    private javax.swing.JComboBox<String> comboroomsize;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JComboBox<String> combotranstype;
    private javax.swing.JComboBox<String> combovehiclename;
    private javax.swing.JComboBox<String> combovehicletype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbladdfood;
    private javax.swing.JLabel lbladdpkg;
    private javax.swing.JLabel lbladdroom;
    private javax.swing.JLabel lbladdtransport;
    private javax.swing.JLabel lblavailablethings;
    private javax.swing.JLabel lblfoodname;
    private javax.swing.JLabel lblfoodtype;
    private javax.swing.JLabel lblfoodtype1;
    private javax.swing.JLabel lblhotelname;
    private javax.swing.JLabel lblmodpkg;
    private javax.swing.JLabel lblmodroom;
    private javax.swing.JLabel lblroomsize;
    private javax.swing.JLabel lblroomsize1;
    private javax.swing.JLabel lblroomtype;
    private javax.swing.JLabel lblroomtype1;
    private javax.swing.JLabel lbltotalcost;
    private javax.swing.JLabel lbltranstype;
    private javax.swing.JLabel lblvehiclecost;
    private javax.swing.JLabel lblvehiclename;
    private javax.swing.JLabel lblvehicletype;
    private javax.swing.JTextField txtfoodcost;
    private javax.swing.JTextField txthotelcost;
    private javax.swing.JTextField txtnoofpersons;
    private javax.swing.JTextField txttotalcost;
    private javax.swing.JTextField txtvehiclecost;
    // End of variables declaration//GEN-END:variables
}
