/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class Userlhr extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Connectclass cons = new Connectclass();
    Tbladdpkg tabl = new Tbladdpkg();
    DefaultTableModel d;

    public Userlhr() {
        initComponents();
        cons.Connect();
         tabl.tbl(tbluserlhr);
    }

    public void mouse() {
        d = (DefaultTableModel) tbluserlhr.getModel();
        int sIndex = tbluserlhr.getSelectedRow();
        txtpkgplace.setText(d.getValueAt(sIndex, 0).toString());
        txtnoofdays.setText(d.getValueAt(sIndex, 1).toString());
        txtpkgtype.setText(d.getValueAt(sIndex, 2).toString());
        txthotelname.setText(d.getValueAt(sIndex, 3).toString());
        txtroomtype.setText(d.getValueAt(sIndex, 4).toString());
        txtroomsize.setText(d.getValueAt(sIndex, 5).toString());
        txtfoodtype.setText(d.getValueAt(sIndex, 6).toString());
        txtcostofpkg.setText(d.getValueAt(sIndex, 7).toString());
        btnaddpkg.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblnoofdays = new javax.swing.JLabel();
        lblpkgroomsize = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluserlhr = new javax.swing.JTable();
        lblpkgplace = new javax.swing.JLabel();
        lblpkgcost = new javax.swing.JLabel();
        lblpkgroomtype = new javax.swing.JLabel();
        txtcostofpkg = new javax.swing.JTextField();
        lblpkgtype = new javax.swing.JLabel();
        lblpkghotelname = new javax.swing.JLabel();
        btnaddpkg = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        lblfoodname = new javax.swing.JLabel();
        lblfoodtype1 = new javax.swing.JLabel();
        txthotelname = new javax.swing.JTextField();
        txtpkgtype = new javax.swing.JTextField();
        txtpkgplace = new javax.swing.JTextField();
        txtroomsize = new javax.swing.JTextField();
        txtnoofdays = new javax.swing.JTextField();
        txtroomtype = new javax.swing.JTextField();
        txtfoodtype = new javax.swing.JTextField();
        combofoodname = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblselectpkg = new javax.swing.JLabel();
        selectyourown = new javax.swing.JLabel();
        lblselecttrans = new javax.swing.JLabel();
        lblselectroom = new javax.swing.JLabel();
        lblselectfood = new javax.swing.JLabel();
        lblselecthotel1 = new javax.swing.JLabel();
        lblselectfood1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tourism Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Book Package");
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 160, 30));

        lblnoofdays.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnoofdays.setForeground(new java.awt.Color(255, 255, 255));
        lblnoofdays.setText("No of Days");
        jPanel5.add(lblnoofdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 20));

        lblpkgroomsize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgroomsize.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgroomsize.setText("Room Size");
        jPanel5.add(lblpkgroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 100, 20));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 20));

        tbluserlhr.setBackground(new java.awt.Color(0, 0, 0));
        tbluserlhr.setForeground(new java.awt.Color(255, 255, 255));
        tbluserlhr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Package Place", "No of Days", "Package Type", "Hotel Name", "Room Type", "Room Size", "Food Type", "Package Cost "
            }
        ));
        tbluserlhr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbluserlhrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbluserlhr);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 840, 260));

        lblpkgplace.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgplace.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgplace.setText("Package Place");
        jPanel5.add(lblpkgplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 20));

        lblpkgcost.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgcost.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgcost.setText("Package Cost");
        jPanel5.add(lblpkgcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 100, 20));

        lblpkgroomtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgroomtype.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgroomtype.setText("Room Type");
        jPanel5.add(lblpkgroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 20));
        jPanel5.add(txtcostofpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 220, 30));

        lblpkgtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgtype.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgtype.setText("Package Type");
        jPanel5.add(lblpkgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 20));

        lblpkghotelname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkghotelname.setForeground(new java.awt.Color(255, 255, 255));
        lblpkghotelname.setText("Hotel Name");
        jPanel5.add(lblpkghotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 20));

        btnaddpkg.setBackground(new java.awt.Color(0, 0, 0));
        btnaddpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnaddpkg.setForeground(new java.awt.Color(255, 255, 255));
        btnaddpkg.setText("Confirm");
        btnaddpkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddpkgActionPerformed(evt);
            }
        });
        jPanel5.add(btnaddpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        btncancel.setBackground(new java.awt.Color(0, 0, 0));
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel5.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        lblfoodname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodname.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodname.setText("Food Name");
        jPanel5.add(lblfoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 80, 20));

        lblfoodtype1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodtype1.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodtype1.setText("Food Type");
        jPanel5.add(lblfoodtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 100, 20));
        jPanel5.add(txthotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 220, 30));
        jPanel5.add(txtpkgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 220, 30));
        jPanel5.add(txtpkgplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 220, 30));
        jPanel5.add(txtroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 220, 30));
        jPanel5.add(txtnoofdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, 30));
        jPanel5.add(txtroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 220, 30));
        jPanel5.add(txtfoodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 220, 30));

        combofoodname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu", "Biryani", "Chowmin", "Noodles", "Pasta ", "Eggs Benedict", "Lobster Newburg", "Peach Melba", "Soup", "Ramen", "Potato Chips", "Donuts", "Ice Cream", "Chicken Tenders", "Soft Drinks/Soda", "Pizza", "Oreo Cookies", "French Fries" }));
        jPanel5.add(combofoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 220, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 860, 580));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_24px.png"))); // NOI18N
        jLabel3.setText("Home");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        lblselectpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectpkg.setForeground(new java.awt.Color(255, 255, 255));
        lblselectpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit_property_24px.png"))); // NOI18N
        lblselectpkg.setText("     Select Package");
        lblselectpkg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblselectpkgMouseClicked(evt);
            }
        });
        jPanel2.add(lblselectpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 50));

        selectyourown.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        selectyourown.setForeground(new java.awt.Color(255, 255, 255));
        selectyourown.setText("     Select by your own choice");
        selectyourown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectyourownMouseClicked(evt);
            }
        });
        jPanel2.add(selectyourown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 30));

        lblselecttrans.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselecttrans.setForeground(new java.awt.Color(255, 255, 255));
        lblselecttrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tiles_26px.png"))); // NOI18N
        lblselecttrans.setText("     Select Transport");
        lblselecttrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblselecttransMouseClicked(evt);
            }
        });
        jPanel2.add(lblselecttrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, 40));

        lblselectroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectroom.setForeground(new java.awt.Color(255, 255, 255));
        lblselectroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grid_24px.png"))); // NOI18N
        lblselectroom.setText("     Select Room");
        lblselectroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblselectroomMouseClicked(evt);
            }
        });
        jPanel2.add(lblselectroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, 40));

        lblselectfood.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblselectfood.setForeground(new java.awt.Color(255, 255, 255));
        lblselectfood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        lblselectfood.setText("     Logout");
        lblselectfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblselectfoodMouseClicked(evt);
            }
        });
        jPanel2.add(lblselectfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 140, 60));

        lblselecthotel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselecthotel1.setForeground(new java.awt.Color(255, 255, 255));
        lblselecthotel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/template_26px.png"))); // NOI18N
        lblselecthotel1.setText("     Select Hotel");
        lblselecthotel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblselecthotel1MouseClicked(evt);
            }
        });
        jPanel2.add(lblselecthotel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 210, 50));

        lblselectfood1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectfood1.setForeground(new java.awt.Color(255, 255, 255));
        lblselectfood1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/categorize_24px.png"))); // NOI18N
        lblselectfood1.setText("     Select Food");
        lblselectfood1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblselectfood1MouseClicked(evt);
            }
        });
        jPanel2.add(lblselectfood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, 730));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\taimo\\Downloads\\2s.png")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1190, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbluserlhrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbluserlhrMouseClicked
        // TODO add your handling code here
        mouse();
    }//GEN-LAST:event_tbluserlhrMouseClicked

    private void btnaddpkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddpkgActionPerformed
        // TODO add your handling code here:
//        Adminaddpkg p = new Adminaddpkg();
//        p.adminpkg((String) combopkgplace.getSelectedItem(), Integer.parseInt(txtfoodname.getText()), (String) combopkgtype.getSelectedItem(), (String) combohotelname.getSelectedItem(), (String) comboroomtype.getSelectedItem(), (String) comboroomsize.getSelectedItem(), (String) combofoodtype.getSelectedItem(), Double.parseDouble(txtcostofpkg.getText()));
        tabl.tbl(tbluserlhr);
    }//GEN-LAST:event_btnaddpkgActionPerformed

    private void lblselectpkgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblselectpkgMouseClicked
        // TODO add your handling code here:
        Userv desti=new Userv();
        desti.show();
    }//GEN-LAST:event_lblselectpkgMouseClicked

    private void selectyourownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectyourownMouseClicked
        // TODO add your handling code here:
        Adminchoice choice= new Adminchoice();
        choice.show();
    }//GEN-LAST:event_selectyourownMouseClicked

    private void lblselecttransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblselecttransMouseClicked
        // TODO add your handling code here:
        Adminchoice choice= new Adminchoice();
        choice.show();
    }//GEN-LAST:event_lblselecttransMouseClicked

    private void lblselectroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblselectroomMouseClicked
        // TODO add your handling code here:
        Adminchoice choice= new Adminchoice();
        choice.show();
    }//GEN-LAST:event_lblselectroomMouseClicked

    private void lblselectfoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblselectfoodMouseClicked
        // TODO add your handling code here:
        Homescreen screen=new Homescreen();
        screen.show();
    }//GEN-LAST:event_lblselectfoodMouseClicked

    private void lblselecthotel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblselecthotel1MouseClicked
        // TODO add your handling code here:
        Adminchoice choice= new Adminchoice();
        choice.show();
    }//GEN-LAST:event_lblselecthotel1MouseClicked

    private void lblselectfood1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblselectfood1MouseClicked
        // TODO add your handling code here:
        Adminchoice choice= new Adminchoice();
        choice.show();
    }//GEN-LAST:event_lblselectfood1MouseClicked

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        Userview view=new Userview();
        view.show();
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userlhr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userlhr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userlhr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userlhr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userlhr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddpkg;
    private javax.swing.JButton btncancel;
    private javax.swing.JComboBox<String> combofoodname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfoodname;
    private javax.swing.JLabel lblfoodtype1;
    private javax.swing.JLabel lblnoofdays;
    private javax.swing.JLabel lblpkgcost;
    private javax.swing.JLabel lblpkghotelname;
    private javax.swing.JLabel lblpkgplace;
    private javax.swing.JLabel lblpkgroomsize;
    private javax.swing.JLabel lblpkgroomtype;
    private javax.swing.JLabel lblpkgtype;
    private javax.swing.JLabel lblselectfood;
    private javax.swing.JLabel lblselectfood1;
    private javax.swing.JLabel lblselecthotel1;
    private javax.swing.JLabel lblselectpkg;
    private javax.swing.JLabel lblselectroom;
    private javax.swing.JLabel lblselecttrans;
    private javax.swing.JLabel selectyourown;
    private javax.swing.JTable tbluserlhr;
    private javax.swing.JTextField txtcostofpkg;
    private javax.swing.JTextField txtfoodtype;
    private javax.swing.JTextField txthotelname;
    private javax.swing.JTextField txtnoofdays;
    private javax.swing.JTextField txtpkgplace;
    private javax.swing.JTextField txtpkgtype;
    private javax.swing.JTextField txtroomsize;
    private javax.swing.JTextField txtroomtype;
    // End of variables declaration//GEN-END:variables
}
