/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms;

import java.awt.Color;

/**
 *
 * @author taimo
 */
public class Userhotel extends javax.swing.JFrame {

    /**
     * Creates new form Userhotel
     */
    public Userhotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblselectpkg = new javax.swing.JLabel();
        lbluserprofile = new javax.swing.JLabel();
        lblusermodpkg = new javax.swing.JLabel();
        lblusermodroom = new javax.swing.JLabel();
        selectyourown = new javax.swing.JLabel();
        lblselecttrans = new javax.swing.JLabel();
        lblselecthotel = new javax.swing.JLabel();
        lblselectroom = new javax.swing.JLabel();
        lblselectfood = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblhoteltype = new javax.swing.JLabel();
        lblvehiclename = new javax.swing.JLabel();
        lblroomsize = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btnconfirm = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtfoodname = new javax.swing.JTextField();
        lblvehicletype = new javax.swing.JLabel();
        txtvehiclename = new javax.swing.JTextField();
        txtvehiclecost = new javax.swing.JTextField();
        lblfoodname = new javax.swing.JLabel();
        lblroomtype = new javax.swing.JLabel();
        txttotalcost = new javax.swing.JTextField();
        lbltranstype = new javax.swing.JLabel();
        lblvehiclecost = new javax.swing.JLabel();
        lblhotellocation = new javax.swing.JLabel();
        lbltotalcost = new javax.swing.JLabel();
        lblfoodtype = new javax.swing.JLabel();
        combofoodtype = new javax.swing.JComboBox<>();
        combotranstype = new javax.swing.JComboBox<>();
        combovehicletype = new javax.swing.JComboBox<>();
        combohotellocation = new javax.swing.JComboBox<>();
        comboroomtype = new javax.swing.JComboBox<>();
        combohoteltype = new javax.swing.JComboBox<>();
        comboroomsize = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblhotelname = new javax.swing.JLabel();
        txthotelname = new javax.swing.JTextField();
        lblroomsize1 = new javax.swing.JLabel();
        txtfoodname1 = new javax.swing.JTextField();
        lblfoodtype1 = new javax.swing.JLabel();
        txtfoodname2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tourism Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_24px.png"))); // NOI18N
        jLabel3.setText("Home");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        lblselectpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectpkg.setForeground(new java.awt.Color(255, 255, 255));
        lblselectpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit_property_24px.png"))); // NOI18N
        lblselectpkg.setText("     Select Package");
        jPanel2.add(lblselectpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 50));

        lbluserprofile.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbluserprofile.setForeground(new java.awt.Color(255, 255, 255));
        lbluserprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/google_forms_24px.png"))); // NOI18N
        lbluserprofile.setText("      Profile");
        jPanel2.add(lbluserprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 30));

        lblusermodpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblusermodpkg.setForeground(new java.awt.Color(255, 255, 255));
        lblusermodpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        lblusermodpkg.setText("     Modify/Delete Package");
        jPanel2.add(lblusermodpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 40));

        lblusermodroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblusermodroom.setForeground(new java.awt.Color(255, 255, 255));
        lblusermodroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        lblusermodroom.setText("     Modify/Delete Choice");
        jPanel2.add(lblusermodroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 40));

        selectyourown.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        selectyourown.setForeground(new java.awt.Color(255, 255, 255));
        selectyourown.setText("     Select by your own choice");
        jPanel2.add(selectyourown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 30));

        lblselecttrans.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselecttrans.setForeground(new java.awt.Color(255, 255, 255));
        lblselecttrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tiles_26px.png"))); // NOI18N
        lblselecttrans.setText("     Select Transport");
        jPanel2.add(lblselecttrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, 40));

        lblselecthotel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselecthotel.setForeground(new java.awt.Color(255, 255, 255));
        lblselecthotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/template_26px.png"))); // NOI18N
        lblselecthotel.setText("     Select Hotel");
        jPanel2.add(lblselecthotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 210, 50));

        lblselectroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectroom.setForeground(new java.awt.Color(255, 255, 255));
        lblselectroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grid_24px.png"))); // NOI18N
        lblselectroom.setText("     Select Room");
        jPanel2.add(lblselectroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, 40));

        lblselectfood.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectfood.setForeground(new java.awt.Color(255, 255, 255));
        lblselectfood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/categorize_24px.png"))); // NOI18N
        lblselectfood.setText("     Select Food");
        jPanel2.add(lblselectfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 730));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Your Own Choice list");
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 240, 20));

        lblhoteltype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblhoteltype.setForeground(new java.awt.Color(255, 255, 255));
        lblhoteltype.setText("Hotel Type");
        jPanel5.add(lblhoteltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, 20));

        lblvehiclename.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblvehiclename.setForeground(new java.awt.Color(255, 255, 255));
        lblvehiclename.setText("Vehicle Name");
        jPanel5.add(lblvehiclename, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, 20));

        lblroomsize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblroomsize.setForeground(new java.awt.Color(255, 255, 255));
        lblroomsize.setText("Room Size");
        jPanel5.add(lblroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 100, 20));

        btncancel.setBackground(new java.awt.Color(0, 0, 0));
        btncancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Delete");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel5.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 70, -1));

        btnconfirm.setBackground(new java.awt.Color(0, 0, 0));
        btnconfirm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnconfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirm.setText("Edit");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });
        jPanel5.add(btnconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 20));
        jPanel5.add(txtfoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 200, 20));

        lblvehicletype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblvehicletype.setForeground(new java.awt.Color(255, 255, 255));
        lblvehicletype.setText("Vehicle Type");
        jPanel5.add(lblvehicletype, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, 20));
        jPanel5.add(txtvehiclename, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 210, 20));
        jPanel5.add(txtvehiclecost, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 210, 20));

        lblfoodname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodname.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodname.setText("Food Name");
        jPanel5.add(lblfoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 80, 20));

        lblroomtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblroomtype.setForeground(new java.awt.Color(255, 255, 255));
        lblroomtype.setText("Room Type");
        jPanel5.add(lblroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 100, 20));
        jPanel5.add(txttotalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 200, 20));

        lbltranstype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbltranstype.setForeground(new java.awt.Color(255, 255, 255));
        lbltranstype.setText("Transport Type");
        jPanel5.add(lbltranstype, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, 20));

        lblvehiclecost.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblvehiclecost.setForeground(new java.awt.Color(255, 255, 255));
        lblvehiclecost.setText("Vehicle cost");
        jPanel5.add(lblvehiclecost, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 20));

        lblhotellocation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblhotellocation.setForeground(new java.awt.Color(255, 255, 255));
        lblhotellocation.setText("Hotel Location");
        jPanel5.add(lblhotellocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 100, 20));

        lbltotalcost.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbltotalcost.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalcost.setText("Total Cost");
        jPanel5.add(lbltotalcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, 20));

        lblfoodtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodtype.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodtype.setText("Food Cost");
        jPanel5.add(lblfoodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 100, 20));

        combofoodtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combofoodtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combofoodtypeActionPerformed(evt);
            }
        });
        jPanel5.add(combofoodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 200, -1));

        combotranstype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(combotranstype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 210, -1));

        combovehicletype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(combovehicletype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 210, -1));

        combohotellocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(combohotellocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, -1));

        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 200, -1));

        combohoteltype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(combohoteltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 210, -1));

        comboroomsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(comboroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 200, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Transport Type", "Vehicle Type", "Vehicle Name", "Vehicle Cost", "Hotel Name", "Hotel Type", "Hotel Location", "Room Type", "Room Size", "Hotel Cost", "Food Name", "Food Type", "Food Cost", "Total Cost"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 950, 270));

        lblhotelname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblhotelname.setForeground(new java.awt.Color(255, 255, 255));
        lblhotelname.setText("Hotel Name");
        jPanel5.add(lblhotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, 20));
        jPanel5.add(txthotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, 20));

        lblroomsize1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblroomsize1.setForeground(new java.awt.Color(255, 255, 255));
        lblroomsize1.setText("Hotel Cost");
        jPanel5.add(lblroomsize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 100, 20));
        jPanel5.add(txtfoodname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 200, 20));

        lblfoodtype1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfoodtype1.setForeground(new java.awt.Color(255, 255, 255));
        lblfoodtype1.setText("Food Type");
        jPanel5.add(lblfoodtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 100, 20));
        jPanel5.add(txtfoodname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 200, 20));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 950, 580));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\taimo\\Downloads\\2s.png")); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1190, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void combofoodtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combofoodtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combofoodtypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userhotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userhotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userhotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userhotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userhotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JComboBox<String> combofoodtype;
    private javax.swing.JComboBox<String> combohotellocation;
    private javax.swing.JComboBox<String> combohoteltype;
    private javax.swing.JComboBox<String> comboroomsize;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JComboBox<String> combotranstype;
    private javax.swing.JComboBox<String> combovehicletype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblfoodname;
    private javax.swing.JLabel lblfoodtype;
    private javax.swing.JLabel lblfoodtype1;
    private javax.swing.JLabel lblhotellocation;
    private javax.swing.JLabel lblhotelname;
    private javax.swing.JLabel lblhoteltype;
    private javax.swing.JLabel lblroomsize;
    private javax.swing.JLabel lblroomsize1;
    private javax.swing.JLabel lblroomtype;
    private javax.swing.JLabel lblselectfood;
    private javax.swing.JLabel lblselecthotel;
    private javax.swing.JLabel lblselectpkg;
    private javax.swing.JLabel lblselectroom;
    private javax.swing.JLabel lblselecttrans;
    private javax.swing.JLabel lbltotalcost;
    private javax.swing.JLabel lbltranstype;
    private javax.swing.JLabel lblusermodpkg;
    private javax.swing.JLabel lblusermodroom;
    private javax.swing.JLabel lbluserprofile;
    private javax.swing.JLabel lblvehiclecost;
    private javax.swing.JLabel lblvehiclename;
    private javax.swing.JLabel lblvehicletype;
    private javax.swing.JLabel selectyourown;
    private javax.swing.JTextField txtfoodname;
    private javax.swing.JTextField txtfoodname1;
    private javax.swing.JTextField txtfoodname2;
    private javax.swing.JTextField txthotelname;
    private javax.swing.JTextField txttotalcost;
    private javax.swing.JTextField txtvehiclecost;
    private javax.swing.JTextField txtvehiclename;
    // End of variables declaration//GEN-END:variables
}
