package tms;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author taimo
 */
public class Userpackage extends javax.swing.JFrame {

    /**
     * Creates new form Userpackage
     */
    public Userpackage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblselectpkg = new javax.swing.JLabel();
        lbluserprofile = new javax.swing.JLabel();
        lblusermodpkg = new javax.swing.JLabel();
        lblusermodroom = new javax.swing.JLabel();
        selectyourown = new javax.swing.JLabel();
        lblselecttrans = new javax.swing.JLabel();
        lblselecthotel = new javax.swing.JLabel();
        lblselectroom = new javax.swing.JLabel();
        lblselectfood = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lbldiscount = new javax.swing.JLabel();
        lblnoofdays = new javax.swing.JLabel();
        lblpkgroomsize = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btnbook = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbookpkg = new javax.swing.JTable();
        lblpkgplace = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        lblpkgcost = new javax.swing.JLabel();
        lblpkgroomtype = new javax.swing.JLabel();
        txtpkgcost = new javax.swing.JTextField();
        txthotelname = new javax.swing.JTextField();
        lblpkgname = new javax.swing.JLabel();
        txtpkgname = new javax.swing.JTextField();
        lblpkgtype = new javax.swing.JLabel();
        lblpkghotelname = new javax.swing.JLabel();
        lblnoofperson = new javax.swing.JLabel();
        txtnoofperson = new javax.swing.JTextField();
        comboroomsize = new javax.swing.JComboBox<>();
        combopkgplace = new javax.swing.JComboBox<>();
        combopkgtype = new javax.swing.JComboBox<>();
        combohoteltype = new javax.swing.JComboBox<>();
        comboroomtype = new javax.swing.JComboBox<>();
        lblpkghoteltype = new javax.swing.JLabel();
        txtnoofdays1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tourism Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_24px.png"))); // NOI18N
        jLabel3.setText("Home");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        lblselectpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectpkg.setForeground(new java.awt.Color(255, 255, 255));
        lblselectpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit_property_24px.png"))); // NOI18N
        lblselectpkg.setText("     Select Package");
        jPanel2.add(lblselectpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 50));

        lbluserprofile.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbluserprofile.setForeground(new java.awt.Color(255, 255, 255));
        lbluserprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/google_forms_24px.png"))); // NOI18N
        lbluserprofile.setText("      Profile");
        jPanel2.add(lbluserprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 30));

        lblusermodpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblusermodpkg.setForeground(new java.awt.Color(255, 255, 255));
        lblusermodpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        lblusermodpkg.setText("     Modify/Delete Package");
        jPanel2.add(lblusermodpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 40));

        lblusermodroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblusermodroom.setForeground(new java.awt.Color(255, 255, 255));
        lblusermodroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        lblusermodroom.setText("     Modify/Delete Choice");
        jPanel2.add(lblusermodroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 40));

        selectyourown.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        selectyourown.setForeground(new java.awt.Color(255, 255, 255));
        selectyourown.setText("     Select by your own choice");
        jPanel2.add(selectyourown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 30));

        lblselecttrans.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselecttrans.setForeground(new java.awt.Color(255, 255, 255));
        lblselecttrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tiles_26px.png"))); // NOI18N
        lblselecttrans.setText("     Select Transport");
        jPanel2.add(lblselecttrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, 40));

        lblselecthotel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselecthotel.setForeground(new java.awt.Color(255, 255, 255));
        lblselecthotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/template_26px.png"))); // NOI18N
        lblselecthotel.setText("     Select Hotel");
        jPanel2.add(lblselecthotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 210, 50));

        lblselectroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectroom.setForeground(new java.awt.Color(255, 255, 255));
        lblselectroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grid_24px.png"))); // NOI18N
        lblselectroom.setText("     Select Room");
        jPanel2.add(lblselectroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, 40));

        lblselectfood.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectfood.setForeground(new java.awt.Color(255, 255, 255));
        lblselectfood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/categorize_24px.png"))); // NOI18N
        lblselectfood.setText("     Select Food");
        jPanel2.add(lblselectfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, 730));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Book Package");
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 160, 40));

        lbldiscount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbldiscount.setForeground(new java.awt.Color(255, 255, 255));
        lbldiscount.setText("Discount");
        jPanel5.add(lbldiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 20));

        lblnoofdays.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnoofdays.setForeground(new java.awt.Color(255, 255, 255));
        lblnoofdays.setText("No of Days");
        jPanel5.add(lblnoofdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 20));

        lblpkgroomsize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgroomsize.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgroomsize.setText("Room Size");
        jPanel5.add(lblpkgroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 100, 20));

        btncancel.setBackground(new java.awt.Color(0, 0, 0));
        btncancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel5.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 70, -1));

        btnbook.setBackground(new java.awt.Color(0, 0, 0));
        btnbook.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnbook.setForeground(new java.awt.Color(255, 255, 255));
        btnbook.setText("Book");
        btnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookActionPerformed(evt);
            }
        });
        jPanel5.add(btnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 20));

        tblbookpkg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Package Name", "Package Place", "No of Days", "Package Type", "Hotel Type", "Hotel Name", "Room Type", "Room Size", "No of Persons", "Package Cost "
            }
        ));
        jScrollPane1.setViewportView(tblbookpkg);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 840, 280));

        lblpkgplace.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgplace.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgplace.setText("Package Place");
        jPanel5.add(lblpkgplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 20));
        jPanel5.add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 220, 20));

        lblpkgcost.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgcost.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgcost.setText("Package Cost");
        jPanel5.add(lblpkgcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 100, 20));

        lblpkgroomtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgroomtype.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgroomtype.setText("Room Type");
        jPanel5.add(lblpkgroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 100, 20));
        jPanel5.add(txtpkgcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 220, 20));
        jPanel5.add(txthotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 220, 20));

        lblpkgname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgname.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgname.setText("Package Name");
        jPanel5.add(lblpkgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));
        jPanel5.add(txtpkgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 72, 220, 20));

        lblpkgtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkgtype.setForeground(new java.awt.Color(255, 255, 255));
        lblpkgtype.setText("Package Type");
        jPanel5.add(lblpkgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 20));

        lblpkghotelname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkghotelname.setForeground(new java.awt.Color(255, 255, 255));
        lblpkghotelname.setText("Hotel Name");
        jPanel5.add(lblpkghotelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 100, 20));

        lblnoofperson.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnoofperson.setForeground(new java.awt.Color(255, 255, 255));
        lblnoofperson.setText("No of Persons");
        jPanel5.add(lblnoofperson, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 100, 20));
        jPanel5.add(txtnoofperson, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 220, 20));

        comboroomsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(comboroomsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 220, -1));

        combopkgplace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(combopkgplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, -1));

        combopkgtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(combopkgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, -1));

        combohoteltype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(combohoteltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 220, -1));

        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 220, -1));

        lblpkghoteltype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblpkghoteltype.setForeground(new java.awt.Color(255, 255, 255));
        lblpkghoteltype.setText("Hotel Type");
        jPanel5.add(lblpkghoteltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 20));
        jPanel5.add(txtnoofdays1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, 20));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 860, 580));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\taimo\\Downloads\\2s.png")); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1190, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbookActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userpackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userpackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userpackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userpackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userpackage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbook;
    private javax.swing.JButton btncancel;
    private javax.swing.JComboBox<String> combohoteltype;
    private javax.swing.JComboBox<String> combopkgplace;
    private javax.swing.JComboBox<String> combopkgtype;
    private javax.swing.JComboBox<String> comboroomsize;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldiscount;
    private javax.swing.JLabel lblnoofdays;
    private javax.swing.JLabel lblnoofperson;
    private javax.swing.JLabel lblpkgcost;
    private javax.swing.JLabel lblpkghotelname;
    private javax.swing.JLabel lblpkghoteltype;
    private javax.swing.JLabel lblpkgname;
    private javax.swing.JLabel lblpkgplace;
    private javax.swing.JLabel lblpkgroomsize;
    private javax.swing.JLabel lblpkgroomtype;
    private javax.swing.JLabel lblpkgtype;
    private javax.swing.JLabel lblselectfood;
    private javax.swing.JLabel lblselecthotel;
    private javax.swing.JLabel lblselectpkg;
    private javax.swing.JLabel lblselectroom;
    private javax.swing.JLabel lblselecttrans;
    private javax.swing.JLabel lblusermodpkg;
    private javax.swing.JLabel lblusermodroom;
    private javax.swing.JLabel lbluserprofile;
    private javax.swing.JLabel selectyourown;
    private javax.swing.JTable tblbookpkg;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txthotelname;
    private javax.swing.JTextField txtnoofdays1;
    private javax.swing.JTextField txtnoofperson;
    private javax.swing.JTextField txtpkgcost;
    private javax.swing.JTextField txtpkgname;
    // End of variables declaration//GEN-END:variables
}
