package tms;


import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author taimo
 */
public class Userview extends javax.swing.JFrame {

    /**
     * Creates new form userview
     */
    public Userview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblselecthotel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblselectpkg = new javax.swing.JLabel();
        selectyourown = new javax.swing.JLabel();
        lblselecttrans = new javax.swing.JLabel();
        lblselectroom = new javax.swing.JLabel();
        lblselectfood = new javax.swing.JLabel();
        lblselecthotel1 = new javax.swing.JLabel();
        lblselectfood1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tourism Management System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 40));

        lblselecthotel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselecthotel.setForeground(new java.awt.Color(255, 255, 255));
        lblselecthotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/male_user_50px.png"))); // NOI18N
        lblselecthotel.setText("     Welcome Dear User");
        jPanel1.add(lblselecthotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 210, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_24px.png"))); // NOI18N
        jLabel3.setText("Home");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        lblselectpkg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectpkg.setForeground(new java.awt.Color(255, 255, 255));
        lblselectpkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit_property_24px.png"))); // NOI18N
        lblselectpkg.setText("     Select Package");
        lblselectpkg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblselectpkgMouseClicked(evt);
            }
        });
        jPanel2.add(lblselectpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 50));

        selectyourown.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        selectyourown.setForeground(new java.awt.Color(255, 255, 255));
        selectyourown.setText("     Select by your own choice");
        selectyourown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectyourownMouseClicked(evt);
            }
        });
        jPanel2.add(selectyourown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 30));

        lblselecttrans.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselecttrans.setForeground(new java.awt.Color(255, 255, 255));
        lblselecttrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tiles_26px.png"))); // NOI18N
        lblselecttrans.setText("     Select Transport");
        jPanel2.add(lblselecttrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, 40));

        lblselectroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectroom.setForeground(new java.awt.Color(255, 255, 255));
        lblselectroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grid_24px.png"))); // NOI18N
        lblselectroom.setText("     Select Room");
        jPanel2.add(lblselectroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, 40));

        lblselectfood.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblselectfood.setForeground(new java.awt.Color(255, 255, 255));
        lblselectfood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        lblselectfood.setText("     Logout");
        lblselectfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblselectfoodMouseClicked(evt);
            }
        });
        jPanel2.add(lblselectfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 140, 60));

        lblselecthotel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselecthotel1.setForeground(new java.awt.Color(255, 255, 255));
        lblselecthotel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/template_26px.png"))); // NOI18N
        lblselecthotel1.setText("     Select Hotel");
        jPanel2.add(lblselecthotel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 210, 50));

        lblselectfood1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblselectfood1.setForeground(new java.awt.Color(255, 255, 255));
        lblselectfood1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/categorize_24px.png"))); // NOI18N
        lblselectfood1.setText("     Select Food");
        jPanel2.add(lblselectfood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, 730));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Welcome Dear User!");
        jPanel5.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 250, 60));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 400, 180));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\taimo\\Downloads\\2s.png")); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1190, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblselectpkgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblselectpkgMouseClicked
        // TODO add your handling code here:
        
        Userv desti=new Userv();
        desti.show();
    }//GEN-LAST:event_lblselectpkgMouseClicked

    private void selectyourownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectyourownMouseClicked
        // TODO add your handling code here:
        Adminchoice choice= new Adminchoice();
        choice.show();
    }//GEN-LAST:event_selectyourownMouseClicked

    private void lblselectfoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblselectfoodMouseClicked
        // TODO add your handling code here:
        Homescreen screen=new Homescreen();
        screen.show();
    }//GEN-LAST:event_lblselectfoodMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblselectfood;
    private javax.swing.JLabel lblselectfood1;
    private javax.swing.JLabel lblselecthotel;
    private javax.swing.JLabel lblselecthotel1;
    private javax.swing.JLabel lblselectpkg;
    private javax.swing.JLabel lblselectroom;
    private javax.swing.JLabel lblselecttrans;
    private javax.swing.JLabel selectyourown;
    // End of variables declaration//GEN-END:variables
}
